<?php

namespace Acme\DemoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class newPHPClassController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\DemoBundle\Controller\newPHPClassController();
        return $instance;
    }
}
