<?php

namespace Proyecto\ExtensionBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExtensionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Proyecto\ExtensionBundle\Controller\ExtensionController();
        return $instance;
    }
}
