proyecto:
    pattern:  /
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:index" }

proyecto_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:show" }

proyecto_new:
    pattern:  /new
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:new" }

proyecto_create:
    pattern:  /create
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:create" }
    requirements: { _method: post }

proyecto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:edit" }

proyecto_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:update" }
    requirements: { _method: post }

proyecto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:delete" }
    requirements: { _method: post }
    
proyecto_map:
    pattern:  /map
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:map" }
    
proyecto_mapFilter:
    pattern:  /map/filter
    defaults: { _controller: "ProyectoExtensionBundle:Proyecto:mapFilter" }